### ISSUE TITLE
Gene expression in each cell type for each sample

### ISSUE THREAD

**Issue by RandallJEllis** [Sun-lab/CARseq#1]
Hello, thanks for creating this useful package. I am able to run the `run_CARseq` function and obtain the p-values, padj, FC, coefficients, etc. but I am wondering how to obtain the deconvolved expression values? That is, for each sample, the expression of each gene in each deconvolved cell type. Is this possible?

**Comment by chongjin** [comment]
Hi, Thank you for using our package. To obtain the deconvolved expression value _for each sample_ in the form of model fitted values, you could take the `shrunken_coefficients` object giving the empirical Bayes coefficient estimates inside the `run_CARseq` function return value, extract the columns representing cell-type-specific and cell-type-independent coefficients in the `formula`, and calculate the fitted cell-type-specific expression values based on sample-specific covariates. Please let me know if you need further help.

**Comment by RandallJEllis** [comment]
Sorry for missing this, I would really appreciate further help. I'm aware that `shrunken_coefficients` is one of the resulting outputs from `run_CARseq` and can extract the columns you mentioned, but I'm not sure how to "calculate the fitted cell-type-specific expression values based on sample-specific covariates." Any help is appreciated.

**Comment by chongjin** [comment]
You can try the following code snippet that extends on the example in `run_CARseq` and calculates the expression of each gene in each deconvolved cell type:
```
library(CARseq)

data("n50DE221rep1")
observed_read_count = n50DE221rep1$observed_read_count[1:10,]
# As an example, run only the first 10 genes among the all 10,000 genes to save time:
res = run_CARseq(count_matrix = observed_read_count,
                 cellular_proportions = n50DE221rep1$rho,
                 groups = gl(2, 25),
                 formula = ~ RIN,
                 data = n50DE221rep1$clinical_variables,
                 read_depth = n50DE221rep1$d,
                 shrunken_lfc = TRUE,
                 cores = 1,
                 fix_overdispersion = FALSE,
                 useSocket = TRUE
)
# for example, for the first sample (i = 1):
i = 1
cell_types = c("celltype1", "celltype2", "celltype3")
number_of_genes = nrow(observed_read_count)
groups = gl(2, 25)
cell_type_independent_variables = "RIN"
cell_type_independent_effects = rowSums(
  res$shrunken_coefficients[, cell_type_independent_variables, drop = FALSE] * 
  rep(n50DE221rep1$clinical_variables[i, cell_type_independent_variables], each = number_of_genes))
# cell type specific
group_label = groups[i]
cell_type_effects = matrix(NA, nrow = number_of_genes, ncol = length(cell_types))
for (h in seq_along(cell_types)) {
  cell_type_effects[, h] = 
    res$shrunken_coefficients[, paste0("intercept", ":", cell_types[h])] +
    res$shrunken_coefficients[, paste0(group_label, ":", cell_types[h])]
}
predicted_cell_type_specific_expression = n50DE221rep1$d[i] * exp(cell_type_effects) * 
  rep(n50DE221rep1$rho[i, ], each = number_of_genes) *
  rep(exp(cell_type_independent_effects), times = length(cell_types))
colnames(predicted_cell_type_specific_expression) = cell_types
rownames(predicted_cell_type_specific_expression) = rownames(observed_read_count)
# You can compare the predicted_expression to observed_read_count[, i]
```
