### ISSUE TITLE
Cannot debug error

### ISSUE THREAD

**Issue by operantBoxFiend** [Sun-lab/CARseq#2]
Hello! The following error came from running the run_CARseq  function with normalized bulk RNA-seq counts, cell fractions, and group labels:

Gene 16479 of 16479 has been processed at 2022-05-27 15:53:46 [1st pass]
Error in result_list[[j]] : subscript out of bounds
Calls: run_CARseq
Execution halted

Despite attempts to debug we cannot find where the issue is on our end. Please advise.

**Comment by chongjin** [comment]
Hi! You are seeing the error message because CARseq is designed to be used with raw read counts of bulk RNA-seq. Please use raw read counts if you have them available. If you only have normalized read counts, you can try a method called TOAST: https://github.com/ziyili20/TOAST.
